const OPTION_NAMES = {
    USE_LINKED_STYLEGUIDES: "useLinkedStyleguides",
    COLOR_FORMAT: "colorFormat",
    SHOW_DEFAULT_VALUES: "showDefaultValues",
    SHOW_DIMENSIONS: "showDimensions",
    UNITLESS_LINE_HEIGHT: "unitlessLineHeight",
    MIXIN: "mixin"
};

const LANG = "sass";

const COPYRIGHT = `    Generated by Zeplin
    Copyright (C) ${new Date().getFullYear()} - present Zeplin\n
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at\n
       http://www.apache.org/licenses/LICENSE-2.0\n
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.\n`;

export { COPYRIGHT, LANG, OPTION_NAMES };